### ISSUE TITLE
Assets for components not being included in styleguide

### ISSUE THREAD

**Issue by dahliacreative** [jgnatch/mountain_view#25]
When I have a component called 'debate' or 'debates' it's assets (sass / js) are not showing up in the styleguide, the html/yml works fine but just no assets. Works perfectly fine if I rename it to something else though.

Really weird, any ideas?

**Comment by kitop** [comment]
@dahliacreative Wow, that is really weird!
Do you happen to have another file named debate or debates in the normal `app/assets/{javascripts,stylesheets}` directories?

**Comment by tombeynon** [comment]
I've noticed at least once where a stylesheet or javascript wasn't included (with no error or explanation). One example was `poll/poll.js` not getting included. I was able to fix this by changing this line..

https://github.com/jgnatch/mountain_view/blob/master/app/assets/javascripts/mountain_view.js.erb#L6

```
require_asset "#{component}/#{component}.js"
```

Happy to submit a PR for this, but we should probably do the same for stylesheets, and I'm wary of fixing the extension since you could have `scss`, `sass` or `css`. What do you guys think?

**Comment by kitop** [comment]
@tombeynon interesting. Will give that a try! Thanks a lot!!

**Comment by tombeynon** [comment]
I suspect this is fixed now. @dahliacreative don't suppose you could test this debate example again easily?

**Comment by kitop** [comment]
@dahliacreative @tombeynon I'll close the issue. Feel free to comment or re-open it if still failing!
